# Created by: Alex Babutin <a.babutin@rambler-co.ru>
# $FreeBSD$

PORTNAME=	aerospike
PORTVERSION=	2.0.2
CATEGORIES=	devel python
MASTER_SITES=	http://freebsd.dev.rambler.ru/distfiles/rambler/
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	a.babutin@rambler-co.ru
COMMENT=	Aerospike Client Library for Python

USES=		python
USE_PYTHON=	distutils

.include <bsd.port.mk>
